package srcr1;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.StringTokenizer;

import javax.swing.DefaultComboBoxModel;

import se.sics.jasper.Query;
import se.sics.jasper.SICStus;
import se.sics.jasper.SPException;

/**
 *
 * @author Rui Rua-PC
 */
public class Servico extends javax.swing.JFrame {
    
	int vez; 
    SICStus sp;
    ArrayList<String> demos;
    String path =  "C:\\Users\\Admin-PC\\Dropbox\\SRCR-Trabalho\\TP2\\tp2Atual.pl";
   public Servico() {
     initComponents();
     this.demos= new ArrayList<>();
     this.vez=0;
     try {
			this.sp = new SICStus();
		} catch (SPException e) {
			// TODO Auto-generated catch block
			jOptionPane1.showMessageDialog(jOptionPane1,"Reveja os campos que inseriu", "Erro", jOptionPane1.ERROR_MESSAGE);
		}
	try {
		this.sp.load(path);
		} catch (SPException e) {
			// TODO Auto-generated catch block
			jOptionPane1.showMessageDialog(jOptionPane1,"Reveja os campos que inseriu", "Erro", jOptionPane1.ERROR_MESSAGE);
		}
     
     updateCombo();
     updateCombo1();
     updateCombo2();
     updateCombo3();
   
   
   
   }

   private void updateCombo(){
      jComboBox1.removeAllItems();
     
      DefaultComboBoxModel<String> dcm = new DefaultComboBoxModel<>();
      
     
           dcm.addElement("utente");
           dcm.addElement("servico");
           dcm.addElement("consulta");
       
      
      jComboBox1.setModel(dcm);
     
 
   }
   
   private void updateCombo1(){
       
       jComboBox2.removeAllItems();
       
       DefaultComboBoxModel<String> dcm = new DefaultComboBoxModel<>();
       
      
            dcm.addElement("utente");
            dcm.addElement("servico");
            dcm.addElement("consulta");
        
       
      
       jComboBox2.setModel(dcm);
      
    }
   
   private void updateCombo2(){
     
       jComboBox3.removeAllItems();
       DefaultComboBoxModel<String> dcm = new DefaultComboBoxModel<>();
       
      
            dcm.addElement("utente");
            dcm.addElement("servico");
            dcm.addElement("consulta");
     
       jComboBox3.setModel(dcm);
  
    }
   
   
   private void updateCombo3(){
     
       comboListing.removeAllItems();
       DefaultComboBoxModel<String> dcm = new DefaultComboBoxModel<>();
       
      
            dcm.addElement("utente");
            dcm.addElement("servico");
            dcm.addElement("consulta");
     
       comboListing.setModel(dcm);
  
    }
    
   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
   private void initComponents() {

       jLabel5 = new javax.swing.JLabel();
       jScrollPane1 = new javax.swing.JScrollPane();
       jTextArea1 = new javax.swing.JTextArea();
       jButton2 = new javax.swing.JButton();
       jOptionPane1 = new javax.swing.JOptionPane();
       jl10 = new javax.swing.JLabel();
       jl11 = new javax.swing.JLabel();
       jl9 = new javax.swing.JLabel();
       jl15 = new javax.swing.JLabel();
       jCheckBox3 = new javax.swing.JCheckBox();
       jLabel1 = new javax.swing.JLabel();
       jTextField1 = new javax.swing.JTextField();
       jLabel2 = new javax.swing.JLabel();
       jLabel3 = new javax.swing.JLabel();
       jTextField2 = new javax.swing.JTextField();
       jLabel4 = new javax.swing.JLabel();
       ok2 = new javax.swing.JButton();
       ok1 = new javax.swing.JButton();
       ok3 = new javax.swing.JButton();
       jComboBox1 = new javax.swing.JComboBox();
       jComboBox2 = new javax.swing.JComboBox();
       jComboBox3 = new javax.swing.JComboBox();
       jTextField13 = new javax.swing.JTextField();
       c1 = new javax.swing.JTextField();
       c2 = new javax.swing.JTextField();
       jTextField16 = new javax.swing.JTextField();
       jTextField17 = new javax.swing.JTextField();
       c3 = new javax.swing.JTextField();
       jTextField19 = new javax.swing.JTextField();
       c4 = new javax.swing.JTextField();
       jTextField21 = new javax.swing.JTextField();
       jTextField22 = new javax.swing.JTextField();
       jLabel6 = new javax.swing.JLabel();
       jl1 = new javax.swing.JLabel();
       jl2 = new javax.swing.JLabel();
       jl3 = new javax.swing.JLabel();
       jl4 = new javax.swing.JLabel();
       jl6 = new javax.swing.JLabel();
       jl12 = new javax.swing.JLabel();
       jl13 = new javax.swing.JLabel();
       jl14 = new javax.swing.JLabel();
       jl16 = new javax.swing.JLabel();
       jl8 = new javax.swing.JLabel();
       jl5 = new javax.swing.JLabel();
       jl7 = new javax.swing.JLabel();
       jCheckBox1 = new javax.swing.JCheckBox();
       jCheckBox2 = new javax.swing.JCheckBox();
       jCheckBox4 = new javax.swing.JCheckBox();
       jLabel7 = new javax.swing.JLabel();
       testar = new javax.swing.JButton();
       jScrollPane2 = new javax.swing.JScrollPane();
       areaTexto = new javax.swing.JTextArea();
       comboListing = new javax.swing.JComboBox();
       jLabel8 = new javax.swing.JLabel();
       jButton1 = new javax.swing.JButton();
       testaLista = new javax.swing.JButton();

       jLabel5.setText("jLabel5");

       jTextArea1.setColumns(20);
       jTextArea1.setRows(5);
       jScrollPane1.setViewportView(jTextArea1);

       jButton2.setText("jButton2");

       jl10.setText(" -----------");

       jl11.setText(" -----------");

       jl9.setText(" -----------");

       jl15.setText(" -----------");

       setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

       jLabel1.setText("Serviço de Manutenção de utentes");

       jTextField1.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jTextField1ActionPerformed(evt);
           }
       });

       jLabel2.setText("Inserção:");

       jLabel3.setText("Remoção:");

       jTextField2.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jTextField2ActionPerformed(evt);
           }
       });

       jLabel4.setText("Consultar:");

       ok2.setText("Ok");
       ok2.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               ok2ActionPerformed(evt);
           }
       });

       ok1.setText("Ok");
       ok1.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               ok1ActionPerformed(evt);
           }
       });

       ok3.setText("Ok");
       ok3.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               ok3ActionPerformed(evt);
           }
       });

       jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
       jComboBox1.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jComboBox1ActionPerformed(evt);
           }
       });

       jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
       jComboBox2.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jComboBox2ActionPerformed(evt);
           }
       });

       jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
       jComboBox3.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jComboBox3ActionPerformed(evt);
           }
       });

       jTextField13.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jTextField13ActionPerformed(evt);
           }
       });

       c1.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               c1ActionPerformed(evt);
           }
       });

       c2.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               c2ActionPerformed(evt);
           }
       });

       jTextField16.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jTextField16ActionPerformed(evt);
           }
       });

       jTextField17.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jTextField17ActionPerformed(evt);
           }
       });

       c3.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               c3ActionPerformed(evt);
           }
       });

       jTextField19.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jTextField19ActionPerformed(evt);
           }
       });

       c4.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               c4ActionPerformed(evt);
           }
       });

       jTextField21.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jTextField21ActionPerformed(evt);
           }
       });

       jTextField22.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jTextField22ActionPerformed(evt);
           }
       });

       jl1.setText(" -----------");

       jl2.setText(" -----------");

       jl3.setText(" -----------");

       jl4.setText(" -----------");

       jl6.setText(" -----------");

       jl12.setText(" -----------");

       jl13.setText(" -----------");

       jl14.setText(" -----------");

       jl16.setText(" -----------");

       jl8.setText(" -----------");

       jl5.setText(" -----------");

       jl7.setText(" -----------");

       jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jCheckBox4ActionPerformed(evt);
           }
       });

       jLabel7.setText("Testar vários:");

       testar.setText("Testar vários");
       testar.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               testarActionPerformed(evt);
           }
       });

       areaTexto.setColumns(20);
       areaTexto.setRows(5);
       jScrollPane2.setViewportView(areaTexto);

       comboListing.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
       comboListing.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               comboListingActionPerformed(evt);
           }
       });

       jLabel8.setText("Listar:");

       jButton1.setText("Listar");
       jButton1.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton1ActionPerformed(evt);
           }
       });

       testaLista.setText("Testar Lista");
       testaLista.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               testaListaActionPerformed(evt);
           }
       });

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(layout.createSequentialGroup()
                       .addGap(11, 11, 11)
                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                           .addGroup(layout.createSequentialGroup()
                               .addComponent(jCheckBox4)
                               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                               .addComponent(jLabel4))
                           .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                               .addGroup(layout.createSequentialGroup()
                                   .addComponent(jCheckBox1)
                                   .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                   .addComponent(jLabel2))
                               .addGroup(layout.createSequentialGroup()
                                   .addComponent(jCheckBox2)
                                   .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                   .addComponent(jLabel3))))
                       .addGap(18, 18, 18)
                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                   .addComponent(jLabel7))
               .addGap(54, 54, 54)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(layout.createSequentialGroup()
                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addGroup(layout.createSequentialGroup()
                               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                   .addComponent(jTextField2)
                                   .addComponent(jTextField1)
                                   .addComponent(c1)
                                   .addComponent(jl5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                               .addGap(18, 18, 18)
                               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(layout.createSequentialGroup()
                                       .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                       .addGap(0, 0, Short.MAX_VALUE))
                                   .addGroup(layout.createSequentialGroup()
                                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                           .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                           .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                           .addComponent(jl6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                           .addGroup(layout.createSequentialGroup()
                               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(jl16, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jl1))
                               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(layout.createSequentialGroup()
                                       .addGap(18, 18, 18)
                                       .addComponent(jl14, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                   .addGroup(layout.createSequentialGroup()
                                       .addGap(18, 18, 18)
                                       .addComponent(jl2)))
                               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addGroup(layout.createSequentialGroup()
                               .addComponent(jl12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                               .addGap(275, 275, 275))
                           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                   .addGroup(layout.createSequentialGroup()
                                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                           .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                           .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                           .addComponent(jl3))
                                       .addGap(18, 18, 18)
                                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                           .addGroup(layout.createSequentialGroup()
                                               .addComponent(c4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                               .addComponent(ok1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                           .addGroup(layout.createSequentialGroup()
                                               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                   .addComponent(jl4)
                                                   .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                   .addComponent(jl13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                               .addComponent(ok2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                   .addGroup(layout.createSequentialGroup()
                                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                           .addGroup(layout.createSequentialGroup()
                                               .addComponent(jl7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                               .addComponent(jl8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                           .addGroup(layout.createSequentialGroup()
                                               .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                               .addGap(18, 18, 18)
                                               .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                       .addComponent(ok3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                               .addGap(71, 71, 71))))
                   .addGroup(layout.createSequentialGroup()
                       .addGap(158, 158, 158)
                       .addComponent(jLabel6)
                       .addContainerGap())))
           .addGroup(layout.createSequentialGroup()
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(layout.createSequentialGroup()
                       .addGap(262, 262, 262)
                       .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                   .addGroup(layout.createSequentialGroup()
                       .addGap(30, 30, 30)
                       .addComponent(jLabel8)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                       .addComponent(comboListing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addGap(18, 18, 18)
                       .addComponent(jButton1)
                       .addGap(0, 0, Short.MAX_VALUE)))
               .addGap(279, 279, 279))
           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
               .addGap(0, 0, Short.MAX_VALUE)
               .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGap(341, 341, 341))
           .addGroup(layout.createSequentialGroup()
               .addContainerGap()
               .addComponent(testar)
               .addGap(29, 29, 29)
               .addComponent(testaLista)
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(layout.createSequentialGroup()
                       .addContainerGap()
                       .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                       .addComponent(jLabel6))
                   .addGroup(layout.createSequentialGroup()
                       .addGap(36, 36, 36)
                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           .addComponent(comboListing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(jLabel8)
                           .addComponent(jButton1))
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                       .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jl5)
                   .addComponent(jl6)
                   .addComponent(jl8)
                   .addComponent(jl7)
                   .addComponent(jLabel7))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(layout.createSequentialGroup()
                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(jLabel2)
                           .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(ok3))
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           .addComponent(jl14)
                           .addComponent(jl13)
                           .addComponent(jl12)
                           .addComponent(jl16))
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                   .addGroup(layout.createSequentialGroup()
                                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                           .addComponent(jLabel3)
                                           .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                           .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                           .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                           .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                           .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                           .addComponent(ok2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                           .addComponent(jl1)
                                           .addComponent(jl2)
                                           .addComponent(jl3)
                                           .addComponent(jl4))
                                       .addGap(3, 3, 3))
                                   .addGroup(layout.createSequentialGroup()
                                       .addComponent(jCheckBox2)
                                       .addGap(26, 26, 26)))
                               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(ok1)
                                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                       .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                       .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                       .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                       .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                       .addComponent(c4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                       .addComponent(jLabel4))))
                           .addComponent(jCheckBox4, javax.swing.GroupLayout.Alignment.TRAILING)))
                   .addComponent(jCheckBox1))
               .addGap(28, 28, 28)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(testar)
                   .addComponent(testaLista))
               .addContainerGap())
       );

       pack();
   }// </editor-fold>                        

   private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {                                            
       // TODO add your handling code here:
   }                                           

   private void ok2ActionPerformed(java.awt.event.ActionEvent evt) {                                    
       // TODO add your handling code here:
       
    
        String x,x1,x2,x3,x4,query;
         if(jComboBox2.getSelectedItem()==null||jComboBox2.getSelectedItem()==null )  {
           jOptionPane1.showMessageDialog(jOptionPane1,"Nao selecionou opçao", "ERROR", jOptionPane1.ERROR_MESSAGE);
           return;
      
      }

      if(jCheckBox2.isSelected())
          {
         x = ((String)jComboBox2.getSelectedItem());
         x1 = jTextField2.getText();
         x2 = jTextField13.getText();
         x3 = jTextField17.getText();
         x4 = jTextField22.getText();
         query = x+"(" + x1 + "," + x2 + "," + x3 + "," +x4 +")";
          this.demos.add(query);
          return;
          
          }
         else
        x = ((String)jComboBox2.getSelectedItem());
          x1 = jTextField2.getText();
         x2 = jTextField13.getText();
         x3 = jTextField17.getText();
         x4 = jTextField22.getText();
        
         if(this.vez==0){
             try {
      			this.sp = new SICStus();
      		} catch (SPException e) {
      			// TODO Auto-generated catch block
      			jOptionPane1.showMessageDialog(jOptionPane1,"Reveja os campos que inseriu", "Erro", jOptionPane1.ERROR_MESSAGE);
      		}
         	
             try {
             	this.sp.load(path);
      		} catch (SPException e) {
      			// TODO Auto-generated catch block
      			jOptionPane1.showMessageDialog(jOptionPane1,"Reveja os campos que inseriu", "Erro", jOptionPane1.ERROR_MESSAGE);
      		}
               }
   	//String query = "servico( oftalmologia, csbraga ).";
   	 query =  "retrocesso("+x+"(" + x1 + "," + x2 + "," + x3 + "," +x4 +")).";
       HashMap map = new HashMap();
      
       boolean b = false;
		try {
			b = this.sp.query(query,map);
		} catch (SPException e) {
			// TODO Auto-generated catch block
			jOptionPane1.showMessageDialog(jOptionPane1,"Reveja os campos que inseriu", "Erro", jOptionPane1.ERROR_MESSAGE);
		}
       
      String xx = "Resultado :" +b;
       if(b)
       { 
           jOptionPane1.showMessageDialog(jOptionPane1,xx, "Resultado", jOptionPane1.WARNING_MESSAGE);
       }
       else {
        
           jOptionPane1.showMessageDialog(jOptionPane1,xx, "Resultado", jOptionPane1.ERROR_MESSAGE);
       }  
        
      
       
       
      jButton1ActionPerformed(null);
       
   }                                   

   private void ok1ActionPerformed(java.awt.event.ActionEvent evt) {                                    
     
     String x,x1,x2,x3,x4,queryS;
         if(jComboBox3.getSelectedItem()==null||jComboBox3.getSelectedItem()==null )  {
           jOptionPane1.showMessageDialog(jOptionPane1,"Nao selecionou opçao", "ERROR", jOptionPane1.ERROR_MESSAGE);
           return;
      
      }

      if(jCheckBox4.isSelected())
          {
         x = ((String)jComboBox3.getSelectedItem());
         x1 = c1.getText();
         x2 = c2.getText();
         x3 = c3.getText();
         x4 = c4.getText();
        String qquery = x+"(" + x1 + "," + x2 + "," + x3 + "," +x4 +")";
          this.demos.add(qquery);
          return;
          
          }
         else
        x = ((String)jComboBox3.getSelectedItem());
         x1 = c1.getText();
         x2 = c2.getText();
         x3 = c3.getText();
         x4 = c4.getText();
        
       try {
			this.sp = new SICStus();
		} catch (SPException e) {
			// TODO Auto-generated catch block
			jOptionPane1.showMessageDialog(jOptionPane1,"Reveja os campos que inseriu", "Erro", jOptionPane1.ERROR_MESSAGE);
		}
   	
       try {
       	this.sp.load(path);
		} catch (SPException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
   	
   	 queryS = "demo("+x+"(" + x1 + "," + x2 + "," + x3 + "," +x4 +"), R).";
   	 System.out.print(queryS);
		HashMap map = new HashMap();
	
		try {
			Query query = this.sp.openPrologQuery(queryS,map);
			try {
				while (query.nextSolution()) {
					x = (map.toString());
					System.out.print(x);
					}
			} catch (Exception e) {
				// TODO Auto-generated catch block
				jOptionPane1.showMessageDialog(jOptionPane1,"Reveja os campos que inseriu", "Erro", jOptionPane1.ERROR_MESSAGE);
			}
				try {
					query.close();
				} catch (NoSuchMethodException e) {
					// TODO Auto-generated catch block
					jOptionPane1.showMessageDialog(jOptionPane1,"Reveja os campos que inseriu", "Erro", jOptionPane1.ERROR_MESSAGE);
				} catch (InterruptedException e) {
					// TODO Auto-generated catch block
					jOptionPane1.showMessageDialog(jOptionPane1,"Reveja os campos que inseriu", "Erro", jOptionPane1.ERROR_MESSAGE);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					jOptionPane1.showMessageDialog(jOptionPane1,"Reveja os campos que inseriu", "Erro", jOptionPane1.ERROR_MESSAGE);
				}
			
			
		} catch (SPException e) {
			// TODO Auto-generated catch block
			jOptionPane1.showMessageDialog(jOptionPane1,"Reveja os campos que inseriu", "Erro", jOptionPane1.ERROR_MESSAGE);
		}
       
      String xx = "Resultado :" +x;
     
        
           jOptionPane1.showMessageDialog(jOptionPane1,xx, "Resultado", jOptionPane1.WARNING_MESSAGE);
      
        
       
       
   }                                   

   private void ok3ActionPerformed(java.awt.event.ActionEvent evt) {                                    
       // TODO add your handling code here:
      // TODO add your handling code here:
       String x,x1,x2,x3,x4,query;
         if(jComboBox1.getSelectedItem()==null||jComboBox1.getSelectedItem()==null )  {
           jOptionPane1.showMessageDialog(jOptionPane1,"Nao selecionou opçao", "ERROR", jOptionPane1.ERROR_MESSAGE);
           return;
      
      }

      if(jCheckBox1.isSelected())
          {
         x = ((String)jComboBox1.getSelectedItem());
         x1 = jTextField1.getText();
         x2 = jTextField21.getText();
         x3 = jTextField16.getText();
         x4 = jTextField19.getText();
         query = x+"(" + x1 + "," + x2 + "," + x3 + "," +x4 +")";
          this.demos.add(query);
          return;
          
          }
         else
        x = ((String)jComboBox1.getSelectedItem());
        x1 = jTextField1.getText();
         x2 = jTextField21.getText();
         x3 = jTextField16.getText();
         x4 = jTextField19.getText();
        
         if(this.vez==0){
       try {
			this.sp = new SICStus();
		} catch (SPException e) {
			// TODO Auto-generated catch block
			jOptionPane1.showMessageDialog(jOptionPane1,"Reveja os campos que inseriu", "Erro", jOptionPane1.ERROR_MESSAGE);
		}
   	
       try {
       	this.sp.load(path);
		} catch (SPException e) {
			// TODO Auto-generated catch block
			jOptionPane1.showMessageDialog(jOptionPane1,"Reveja os campos que inseriu", "Erro", jOptionPane1.ERROR_MESSAGE);
		}
         }
   	//String query = "servico( oftalmologia, csbraga ).";
   	 query =  "registar("+x+"(" + x1 + "," + x2 + "," + x3 + "," +x4 +")).";
       System.out.println(query);
   	 HashMap map = new HashMap();
      
       boolean b = false;
		try {
			b = this.sp.query(query,map);
		} catch (SPException e) {
			// TODO Auto-generated catch block
			jOptionPane1.showMessageDialog(jOptionPane1,"Reveja os campos que inseriu", "Erro", jOptionPane1.ERROR_MESSAGE);
		}
       
      String xx = "Resultado :" +b;
      System.out.println(xx);
       if(b)
       { 
           jOptionPane1.showMessageDialog(jOptionPane1,xx, "Resultado", jOptionPane1.WARNING_MESSAGE);
       }
       else {
        
           jOptionPane1.showMessageDialog(jOptionPane1,xx, "Resultado", jOptionPane1.ERROR_MESSAGE);
       }  
        
       jButton1ActionPerformed(null);
       
   }                                   

   private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
       // TODO add your handling code here:
   }                                           

   private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {                                             
       // TODO add your handling code here:
   }                                            

   private void c1ActionPerformed(java.awt.event.ActionEvent evt) {                                   
       // TODO add your handling code here:
   }                                  

   private void c2ActionPerformed(java.awt.event.ActionEvent evt) {                                   
       // TODO add your handling code here:
   }                                  

   private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {                                             
       // TODO add your handling code here:
   }                                            

   private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {                                             
       // TODO add your handling code here:
   }                                            

   private void c3ActionPerformed(java.awt.event.ActionEvent evt) {                                   
       // TODO add your handling code here:
   }                                  

   private void jTextField19ActionPerformed(java.awt.event.ActionEvent evt) {                                             
       // TODO add your handling code here:
   }                                            

   private void c4ActionPerformed(java.awt.event.ActionEvent evt) {                                   
       // TODO add your handling code here:
   }                                  

   private void jTextField21ActionPerformed(java.awt.event.ActionEvent evt) {                                             
       // TODO add your handling code here:
   }                                            

   private void jTextField22ActionPerformed(java.awt.event.ActionEvent evt) {                                             
       // TODO add your handling code here:
   }                                            

   private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
       // TODO add your handling code here:
       if(jComboBox1.getSelectedIndex()==0){
        
        jl5.setText("IdUtente");
        jl6.setText("Nome");
        jl7.setText("Idade");
        jl8.setText("Morada");
        
        return;
        }
        
        if(jComboBox1.getSelectedIndex()==1){
        
        jl5.setText("IdServico");
        jl6.setText("Especialidade");
        jl7.setText("Instituição");
        jl8.setText("Cidade");
        
        return;
        }
       
       if(jComboBox1.getSelectedIndex()==2){
        
        jl5.setText("Data");
        jl6.setText("IdUtente");
        jl7.setText("IdServico");
        jl8.setText("Custo");
        
        return;
        }
      
   }                                          

   private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {                                           
       // TODO add your handling code here:
     
          if(jComboBox3.getSelectedIndex()==0){
        
        jl1.setText("IdUtente");
        jl2.setText("Nome");
        jl3.setText("Idade");
        jl4.setText("Morada");
        
        return;
        }
        
        if(jComboBox3.getSelectedIndex()==1){
        
        jl1.setText("IdServico");
        jl2.setText("Especialidade");
        jl3.setText("Instituição");
        jl4.setText("Cidade");
        
        return;
        }
       
       if(jComboBox3.getSelectedIndex()==2){
        
        jl1.setText("Data");
        jl2.setText("IdUtente");
        jl3.setText("IdServico");
        jl4.setText("Custo");
        
        return;
        }
        
       
   }                                          

   private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {                                           
       // TODO add your handling code here:
       
      if(jComboBox2.getSelectedIndex()==0){
        
        jl16.setText("IdUtente");
        jl14.setText("Nome");
        jl12.setText("Idade");
        jl13.setText("Morada");
        
        return;
        }
        
        if(jComboBox2.getSelectedIndex()==1){
        
        jl16.setText("IdServico");
        jl14.setText("Especialidade");
        jl12.setText("Instituição");
        jl13.setText("Cidade");
        
        return;
        }
       
       if(jComboBox2.getSelectedIndex()==2){
        
        jl16.setText("Data");
        jl14.setText("IdUtente");
        jl12.setText("IdServico");
        jl13.setText("Custo");
        
        return;
        }
   }                                          

   private void testarActionPerformed(java.awt.event.ActionEvent evt) {                                       
      // TODO add your handling code here:
       if(this.demos.size()==0)return;
      String x ="";
       for (int i = 0; i < this.demos.size(); i++) {
           x+= this.demos.get(i);
           
           if(!(i+1>=this.demos.size()))
               x+=" e ";
           
       }
       
       try {
			this.sp = new SICStus();
		} catch (SPException e) {
			// TODO Auto-generated catch block
			jOptionPane1.showMessageDialog(jOptionPane1,"Reveja os campos que inseriu", "Erro", jOptionPane1.ERROR_MESSAGE);
		}
       
    
       try {
       	this.sp.load(path);
		} catch (SPException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
       
       String queryS =  "demoC(" + x + ",R).";
       //String queryS = "demoC(utente(1,1,1,1) e utente(1,1,1,1),R).";
  	 System.out.print(queryS);
		HashMap map = new HashMap();
	
		try {
			Query query = this.sp.openPrologQuery(queryS,map);
			try {
				if (query.nextSolution()) {
					x = (map.toString());
					System.out.print(x);
					}
			} catch (Exception e) {
				// TODO Auto-generated catch block
				jOptionPane1.showMessageDialog(jOptionPane1,"Reveja os campos que inseriu", "Erro", jOptionPane1.ERROR_MESSAGE);
			}
		
			
				try {
					query.close();
				} catch (NoSuchMethodException e) {
					// TODO Auto-generated catch block
					jOptionPane1.showMessageDialog(jOptionPane1,"Reveja os campos que inseriu", "Erro", jOptionPane1.ERROR_MESSAGE);
				} catch (InterruptedException e) {
					// TODO Auto-generated catch block
					jOptionPane1.showMessageDialog(jOptionPane1,"Reveja os campos que inseriu", "Erro", jOptionPane1.ERROR_MESSAGE);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					jOptionPane1.showMessageDialog(jOptionPane1,"Reveja os campos que inseriu", "Erro", jOptionPane1.ERROR_MESSAGE);
				}
			
			
		} catch (SPException e) {
			// TODO Auto-generated catch block
			jOptionPane1.showMessageDialog(jOptionPane1,"Reveja os campos que inseriu", "Erro", jOptionPane1.ERROR_MESSAGE);
		}
      
     String xx = "Resultado :" +x;
    
       
          jOptionPane1.showMessageDialog(jOptionPane1,xx, "Resultado", jOptionPane1.WARNING_MESSAGE);
     
       this.demos.clear();
       
       
   }                                      

   private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {                                           
       // TODO add your handling code here:
   }                                          

   private void comboListingActionPerformed(java.awt.event.ActionEvent evt) {                                             
       // TODO add your handling code here:
       
      
       
   }                                            

   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       // TODO add your handling code here:
       
        areaTexto.setText("");
       
       String x = (String)comboListing.getSelectedItem();
       
       String queryS = "listar(" + x +",R).";
      
       if(0==this.vez){
    	   this.vez++;
    	   try {
			this.sp = new SICStus();
		} catch (SPException e) {
			// TODO Auto-generated catch block
			jOptionPane1.showMessageDialog(jOptionPane1,"Reveja os campos que inseriu", "Erro", jOptionPane1.ERROR_MESSAGE);
		}
	try {
		this.sp.load(path);
		} catch (SPException e) {
			// TODO Auto-generated catch block
			jOptionPane1.showMessageDialog(jOptionPane1,"Reveja os campos que inseriu", "Erro", jOptionPane1.ERROR_MESSAGE);
		}
	
       }
       //String queryS = "demoC(utente(1,1,1,1) e utente(1,1,1,1),R).";
  	 System.out.print(queryS);
		HashMap map = new HashMap();
	
		try {
			Query query = this.sp.openPrologQuery(queryS,map);
			try {
				while (query.nextSolution()) {
					x = (map.toString());
					
					//System.out.print(x);
                         
					}
				x=x.replace("{R=.(", "");
				x=x.replace("}", "");
				x=x.replace(",[]", "");
				x=x.replace("/(/(", "");
				
				String delims = ")";
				
				if(comboListing.getSelectedIndex()==2){
					
					delims = "(";
					x=x.replace("),", ",");
					//x=x.replace(")c", "\nc");
					

					StringTokenizer str = new StringTokenizer(x,delims);
					
					while(str.hasMoreElements()){
						
						
						String b = (String)str.nextElement()+")\n";
						System.out.println(b);
						String bb = b.replace(",.","");
						bb=bb.replace("a)\n","a(" );
						bb=bb.replace("))","" );
						
						areaTexto.append(bb);
					}
				}
				
				else{
				StringTokenizer str = new StringTokenizer(x,delims);
				
				while(str.hasMoreElements()){
					
					String b = (String)str.nextElement()+")\n";
				
					String bb = b.replace(",.","");
				
					areaTexto.append(bb);
				}
				
				}
				
			} catch (Exception e) {
				// TODO Auto-generated catch block
				jOptionPane1.showMessageDialog(jOptionPane1,"Reveja os campos que inseriu", "Erro", jOptionPane1.ERROR_MESSAGE);
			}
			
				try {
					query.close();
				} catch (NoSuchMethodException e) {
					// TODO Auto-generated catch block
					jOptionPane1.showMessageDialog(jOptionPane1,"Reveja os campos que inseriu", "Erro", jOptionPane1.ERROR_MESSAGE);
				} catch (InterruptedException e) {
					// TODO Auto-generated catch block
					jOptionPane1.showMessageDialog(jOptionPane1,"Reveja os campos que inseriu", "Erro", jOptionPane1.ERROR_MESSAGE);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					jOptionPane1.showMessageDialog(jOptionPane1,"Reveja os campos que inseriu", "Erro", jOptionPane1.ERROR_MESSAGE);
				}
			
			
		} catch (SPException e) {
			// TODO Auto-generated catch block
			
			jOptionPane1.showMessageDialog(jOptionPane1,"Reveja os campos que inseriu", "Erro", jOptionPane1.ERROR_MESSAGE);
		}
       
   }      
   
   private void testaListaActionPerformed(java.awt.event.ActionEvent evt) {                                           
       // TODO add your handling code here:
       
          if(this.demos.size()==0 ) {   
           jOptionPane1.showMessageDialog(jOptionPane1,"Insira termos na lista", "Erro", jOptionPane1.ERROR_MESSAGE);
           return;
          }
      String x ="";
       for (int i = 0; i < this.demos.size(); i++) {
           x+= this.demos.get(i);
           
           if(!(i+1>=this.demos.size()))
               x+=" , ";
           
       }
       if(vez==0)
       {
           this.vez++;
       try {
			this.sp = new SICStus();
		} catch (SPException e) {
			// TODO Auto-generated catch block
			jOptionPane1.showMessageDialog(jOptionPane1,"Reveja os campos que inseriu", "Erro", jOptionPane1.ERROR_MESSAGE);
		}
       
    
       try {
       	this.sp.load("C:\\Users\\Admin-PC\\Downloads\\SRCR\\tp2.pl");
		} catch (SPException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
       }
       String queryS =  "demoL( ["+ x + "],R).";
       
  	 System.out.print(queryS);
		HashMap map = new HashMap();
	
		try {
			Query query = sp.openPrologQuery(queryS,map);
			try {
				if (query.nextSolution()) {
					x = (map.toString());
					System.out.print(x);
					}
			} catch (Exception e) {
				// TODO Auto-generated catch block
				jOptionPane1.showMessageDialog(jOptionPane1,"Reveja os campos que inseriu", "Erro", jOptionPane1.ERROR_MESSAGE);
			}
		
			
				try {
					query.close();
				} catch (NoSuchMethodException e) {
					// TODO Auto-generated catch block
					jOptionPane1.showMessageDialog(jOptionPane1,"Reveja os campos que inseriu", "Erro", jOptionPane1.ERROR_MESSAGE);
				} catch (InterruptedException e) {
					// TODO Auto-generated catch block
					jOptionPane1.showMessageDialog(jOptionPane1,"Reveja os campos que inseriu", "Erro", jOptionPane1.ERROR_MESSAGE);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					jOptionPane1.showMessageDialog(jOptionPane1,"Reveja os campos que inseriu", "Erro", jOptionPane1.ERROR_MESSAGE);
				}
			
			
		} catch (SPException e) {
			// TODO Auto-generated catch block
			jOptionPane1.showMessageDialog(jOptionPane1,"Reveja os campos que inseriu", "Erro", jOptionPane1.ERROR_MESSAGE);
		}
      
	
     String xxx = x.replace("))", "");
     String bb = xxx.replace("[]))", "");
     String v = bb.replace(".(", "");
     String xx = "Resultado :" +v;
    
       
          jOptionPane1.showMessageDialog(jOptionPane1,xx, "Resultado", jOptionPane1.WARNING_MESSAGE);
     
       this.demos.clear();
      
       
       
       
   }                                          


   /**
    * @param args the command line arguments
    */
    public static void main(String[] args){
       Servico m = new Servico();
       
     
     
       
       m.setVisible(true);
       m.setLocationRelativeTo(null);
   }

   // Variables declaration - do not modify                     
   private javax.swing.JTextArea areaTexto;
   private javax.swing.JTextField c1;
   private javax.swing.JTextField c2;
   private javax.swing.JTextField c3;
   private javax.swing.JTextField c4;
   private javax.swing.JComboBox comboListing;
   private javax.swing.JButton jButton1;
   private javax.swing.JButton jButton2;
   private javax.swing.JCheckBox jCheckBox1;
   private javax.swing.JCheckBox jCheckBox2;
   private javax.swing.JCheckBox jCheckBox3;
   private javax.swing.JCheckBox jCheckBox4;
   private javax.swing.JComboBox jComboBox1;
   private javax.swing.JComboBox jComboBox2;
   private javax.swing.JComboBox jComboBox3;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JLabel jLabel7;
   private javax.swing.JLabel jLabel8;
   private javax.swing.JOptionPane jOptionPane1;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JScrollPane jScrollPane2;
   private javax.swing.JTextArea jTextArea1;
   private javax.swing.JTextField jTextField1;
   private javax.swing.JTextField jTextField13;
   private javax.swing.JTextField jTextField16;
   private javax.swing.JTextField jTextField17;
   private javax.swing.JTextField jTextField19;
   private javax.swing.JTextField jTextField2;
   private javax.swing.JTextField jTextField21;
   private javax.swing.JTextField jTextField22;
   private javax.swing.JLabel jl1;
   private javax.swing.JLabel jl10;
   private javax.swing.JLabel jl11;
   private javax.swing.JLabel jl12;
   private javax.swing.JLabel jl13;
   private javax.swing.JLabel jl14;
   private javax.swing.JLabel jl15;
   private javax.swing.JLabel jl16;
   private javax.swing.JLabel jl2;
   private javax.swing.JLabel jl3;
   private javax.swing.JLabel jl4;
   private javax.swing.JLabel jl5;
   private javax.swing.JLabel jl6;
   private javax.swing.JLabel jl7;
   private javax.swing.JLabel jl8;
   private javax.swing.JLabel jl9;
   private javax.swing.JButton ok1;
   private javax.swing.JButton ok2;
   private javax.swing.JButton ok3;
   private javax.swing.JButton testaLista;
   private javax.swing.JButton testar;
   // End of variables declaration                   
}

